Repository stolostron/governance-policy-framework, pull requests merged in 2021-03, with the labels that each got.

#74 should patch webhook on managed cluster
  test/policy-collection/policy_gatekeeper_operator_downstream_test.go
  test/policy-collection/policy_gatekeeper_operator_test.go
Labels: approved

#78 Disable standalone UI tests
  .travis.yml
  build/run-e2e-tests.sh
Labels: approved, lgtm

#79 Move standalone var to Docker call
  .travis.yml
  build/run-e2e-tests-ui.sh
Labels: approved

#80 Use standalone var directly
  build/run-e2e-tests-ui.sh
Labels: approved, lgtm

#81 increase the time out for gatekeeper invalid ns scenario
  test/policy-collection/policy_gatekeeper_operator_downstream_test.go
  test/policy-collection/policy_gatekeeper_operator_test.go
Labels: approved, lgtm

#82 increase timeout for gatekeeper pod to be running
  test/policy-collection/policy_gatekeeper_operator_downstream_test.go
  test/policy-collection/policy_gatekeeper_operator_test.go
Labels: approved, lgtm

#83 rename config policy controller
  build/run-e2e-tests.sh
  deploy/config-policy-controller/clusterrole.yaml
  deploy/config-policy-controller/clusterrole_binding.yaml
  deploy/config-policy-controller/operator.yaml
  deploy/config-policy-controller/service_account.yaml
Labels: approved, lgtm

#84 Split UI test and run them in parallel
  .travis.yml
  build/clean-up-cluster.sh
  build/patches/certpolicycontroller.json
  build/patches/iampolicycontroller.json
  build/patches/policycontroller.json
  build/run-e2e-tests-ui.sh
Labels: approved, do-not-merge/hold

#85 update crds
  Makefile
  deploy/cert-policy-controller/certificatepolicies_crd.yaml
  deploy/config-policy-controller/policy.open-cluster-management.io_configurationpolicies_crd.yaml
  deploy/crds/apps.open-cluster-management.io_placementrules_crd.yaml
  deploy/crds/policy.open-cluster-management.io_placementbindings_crd.yaml
  deploy/crds/policy.open-cluster-management.io_policies_crd.yaml
  deploy/crds/policy.open-cluster-management.io_policyautomations_crd.yaml
  deploy/iam-policy-controller/iam_policies_crd.yaml
  go.mod
  go.sum
  test/e2e/cert_policy_test.go
  test/e2e/configuration_policy_test.go
  test/e2e/gatekeeper_test.go
  test/e2e/iam_policy_test.go
  test/policy-collection/policy_comp_operator_test.go
  test/policy-collection/policy_gatekeeper_operator_downstream_test.go
  test/policy-collection/policy_gatekeeper_operator_test.go
  test/resources/gatekeeper/policy-gatekeeper.yaml
Labels: approved, lgtm

#86 update test case according to root policy status change
  test/resources/cert_policy/cert-policy-compliant.yaml
  test/resources/cert_policy/cert-policy-noncompliant.yaml
  test/resources/configuration_policy/role-policy-musthave-compliant.yaml
  test/resources/configuration_policy/role-policy-musthave-noncompliant.yaml
  test/resources/configuration_policy/role-policy-mustnothave-compliant.yaml
  test/resources/configuration_policy/role-policy-mustnothave-noncompliant.yaml
  test/resources/configuration_policy/role-policy-mustonlyhave-compliant.yaml
  test/resources/configuration_policy/role-policy-mustonlyhave-noncompliant.yaml
  test/resources/iam_policy/iam-policy-compliant.yaml
  test/resources/iam_policy/iam-policy-noncompliant.yaml
Labels: approved, lgtm
