Repository stolostron/governance-policy-framework, pull requests merged in 2021-12, with the labels that each got.

#217 Patch to remove Gatekeeper dryrun
  test/policy-collection/policy_gatekeeper_operator_downstream_test.go
  test/policy-collection/policy_gatekeeper_operator_test.go
Labels: lgtm, approved, dco-signoff: yes

#220 Specify kubeconfig in dryrun patch
  test/policy-collection/policy_gatekeeper_operator_downstream_test.go
  test/policy-collection/policy_gatekeeper_operator_test.go
Labels: lgtm, approved, dco-signoff: yes

#221 Update group to match resource
  test/policy-collection/policy_gatekeeper_operator_downstream_test.go
  test/policy-collection/policy_gatekeeper_operator_test.go
Labels: lgtm, approved, dco-signoff: yes

#222 [release-2.2] Patch to remove Gatekeeper dryrun
  test/policy-collection/policy_gatekeeper_operator_test.go
Labels: lgtm, do-not-merge/hold, dco-signoff: yes

#224 Lock ginkgo gomega version
  Dockerfile.e2etest
  build/run-e2e-tests.sh
Labels: dco-signoff: yes

#223 [release-2.3] No-op rebuild
  README.md
Labels: lgtm, approved, dco-signoff: yes

#225 Enable debug logs for Policy Template Sync controller
  .gitignore
  Makefile
  deploy/template-sync/README.md
  deploy/template-sync/debug-logs.yaml
  deploy/template-sync/kustomization.yaml
Labels: lgtm, approved, dco-signoff: yes

#226 Patch imagePullPolicy to Always
  build/patch-dev-images.sh
  build/patches/certpolicycontroller.json
  build/patches/iampolicycontroller.json
  build/patches/policycontroller.json
Labels: lgtm, approved, dco-signoff: yes

#228 Update test case to work with latest policy changes
  test/policy-collection/policy_comp_operator_test.go
  test/policy-collection/policy_gatekeeper_operator_downstream_test.go
Labels: lgtm, approved, dco-signoff: yes

#230 [release-2.3] Update test case to work with latest policy changes
  test/policy-collection/policy_collection_suite_test.go
  test/policy-collection/policy_comp_operator_test.go
  test/policy-collection/policy_gatekeeper_operator_downstream_test.go
  test/policy-collection/policy_gatekeeper_operator_test.go
Labels: approved, dco-signoff: yes

#231 [release-2.3] Add `go mod vendor`
  Dockerfile.e2etest
Labels: approved, dco-signoff: yes

#232 [release-2.4] Use 2.4 CRDs for release-2.4 branch
  Makefile
  deploy/cert-policy-controller/certificatepolicies_crd.yaml
Labels: lgtm, approved, dco-signoff: yes
