Repository stolostron/governance-policy-framework, pull requests merged in 2022-01, with the labels that each got.

#234 [release-2.3] Update org references to `stolostron`
  Dockerfile.e2etest
  Makefile
  README.md
  build/ff.sh
  build/run-e2e-tests-policy-framework.sh
  doc/configuration-policy/README.md
  go.mod
  test/policy-collection/policy_comp_operator_test.go
  test/policy-collection/policy_gatekeeper_operator_downstream_test.go
  test/policy-collection/policy_gatekeeper_operator_test.go
Labels: lgtm, approved, dco-signoff: yes

#233 Update org references to `stolostron`
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Dockerfile.e2etest
  Makefile
  README.md
  build/ff.sh
  build/run-e2e-tests-policy-framework.sh
  deploy/cert-policy-controller/README.md
  deploy/config-policy-controller/README.md
  deploy/crds/README.md
  deploy/iam-policy-controller/README.md
  deploy/propagator/README.md
  deploy/spec-sync/README.md
  deploy/status-sync/README.md
  deploy/template-sync/kustomization.yaml
  doc/configuration-policy/README.md
  doc/development.md
  go.mod
  test/e2e/cert_policy_test.go
  test/e2e/configuration_policy_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/gatekeeper_test.go
  test/e2e/iam_policy_test.go
  test/integration/integration_suite_test.go
  test/integration/policy_generator_test.go
  test/integration/policy_info_metric_test.go
  test/integration/policy_report_metric_test.go
  test/policy-collection/policy_collection_suite_test.go
  test/policy-collection/policy_comp_operator_test.go
  test/policy-collection/policy_gatekeeper_operator_downstream_test.go
  test/policy-collection/policy_gatekeeper_operator_test.go
  test/policy-collection/policy_iam_test.go
  test/resources/policy_generator/subscription.yaml
Labels: lgtm, approved

#235 [release-2.4] Update org references to `stolostron`
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  Dockerfile.e2etest
  Makefile
  README.md
  build/ff.sh
  build/run-e2e-tests-policy-framework.sh
  deploy/crds/README.md
  deploy/propagator/README.md
  doc/configuration-policy/README.md
  doc/development.md
  go.mod
  test/e2e/cert_policy_test.go
  test/e2e/configuration_policy_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/gatekeeper_test.go
  test/e2e/iam_policy_test.go
  test/integration/integration_suite_test.go
  test/integration/policy_generator_test.go
  test/integration/policy_info_metric_test.go
  test/integration/policy_report_metric_test.go
  test/policy-collection/policy_collection_suite_test.go
  test/policy-collection/policy_comp_operator_test.go
  test/policy-collection/policy_gatekeeper_operator_downstream_test.go
  test/policy-collection/policy_gatekeeper_operator_test.go
  test/policy-collection/policy_iam_test.go
  test/resources/policy_generator/subscription.yaml
Labels: lgtm, approved, dco-signoff: yes

#238 [release-2.4] Update `governance-policy-propagator` module and go version
  .travis.yml
  Dockerfile.e2etest
  build/patch-dev-images.sh
  build/patches/certpolicycontroller.json
  build/patches/iampolicycontroller.json
  build/patches/policycontroller.json
  deploy/cert-policy-controller/operator.yaml
  deploy/config-policy-controller/operator.yaml
  deploy/iam-policy-controller/operator.yaml
  deploy/spec-sync/operator.yaml
  deploy/status-sync/yamls/operator.yaml
  deploy/template-sync/operator.yaml
  go.mod
  go.sum
  test/common/common.go
  test/e2e/cert_policy_test.go
  test/e2e/configuration_policy_test.go
  test/e2e/gatekeeper_test.go
  test/e2e/iam_policy_test.go
  test/integration/policy_info_metric_test.go
  test/integration/policy_report_metric_test.go
  test/policy-collection/policy_comp_operator_test.go
  test/policy-collection/policy_gatekeeper_operator_downstream_test.go
  test/policy-collection/policy_gatekeeper_operator_test.go
  test/policy-collection/policy_iam_test.go
Labels: lgtm, approved, dco-signoff: yes

#236 Update `governance-policy-propagator` module and go version
  .travis.yml
  Dockerfile.e2etest
  build/patch-dev-images.sh
  build/patches/certpolicycontroller.json
  build/patches/iampolicycontroller.json
  build/patches/policycontroller.json
  go.mod
  go.sum
  test/common/common.go
  test/e2e/cert_policy_test.go
  test/e2e/configuration_policy_test.go
  test/e2e/gatekeeper_test.go
  test/e2e/iam_policy_test.go
  test/integration/policy_info_metric_test.go
  test/integration/policy_report_metric_test.go
  test/policy-collection/policy_comp_operator_test.go
  test/policy-collection/policy_gatekeeper_operator_downstream_test.go
  test/policy-collection/policy_gatekeeper_operator_test.go
  test/policy-collection/policy_iam_test.go
Labels: lgtm, approved, dco-signoff: yes

#240 [release-2.3] Update `github.com/stolostron/governance-policy-propagator`
  .travis.yml
  go.mod
  go.sum
  test/e2e/cert_policy_test.go
  test/e2e/configuration_policy_test.go
  test/e2e/gatekeeper_test.go
  test/e2e/iam_policy_test.go
  test/policy-collection/policy_comp_operator_test.go
  test/policy-collection/policy_gatekeeper_operator_downstream_test.go
  test/policy-collection/policy_gatekeeper_operator_test.go
Labels: lgtm, approved, dco-signoff: yes

#239 install policyset crd in Makefile
  Makefile
Labels: lgtm, approved, dco-signoff: yes

#237 [release-2.2] Update org references to `stolostron`
  .travis.yml
  Dockerfile.e2etest
  Makefile
  README.md
  build/ff.sh
  build/run-e2e-tests-policy-framework.sh
  deploy/cert-policy-controller/operator.yaml
  deploy/config-policy-controller/operator.yaml
  deploy/iam-policy-controller/operator.yaml
  deploy/propagator/operator.yaml
  deploy/spec-sync/operator.yaml
  deploy/status-sync/yamls/operator.yaml
  deploy/template-sync/operator.yaml
  go.mod
  go.sum
  test/e2e/cert_policy_test.go
  test/e2e/configuration_policy_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/gatekeeper_test.go
  test/e2e/iam_policy_test.go
  test/policy-collection/policy_comp_operator_test.go
  test/policy-collection/policy_gatekeeper_operator_test.go
Labels: lgtm, approved, dco-signoff: yes

#241 Do not rebuild and push image again in publish
  .travis.yml
Labels: lgtm, dco-signoff: yes

#244 Fix component name
  .travis.yml
Labels: lgtm, dco-signoff: yes

#247 [release-2.3] Update GRC UI refs to use new org
  Makefile
  build/clean-up-cluster.sh
  build/patch-dev-images.sh
  build/run-e2e-tests-ui.sh
Labels: lgtm, approved, dco-signoff: yes

#248 [release-2.3] Organization rename to `stolostron`
  build/patches/certpolicycontroller.json
  build/patches/iampolicycontroller.json
  build/patches/policycontroller.json
  deploy/cert-policy-controller/operator.yaml
  deploy/config-policy-controller/operator.yaml
  deploy/iam-policy-controller/operator.yaml
  deploy/propagator/operator.yaml
  deploy/spec-sync/operator.yaml
  deploy/status-sync/yamls/operator.yaml
  deploy/template-sync/operator.yaml
  test/e2e/e2e_suite_test.go
Labels: lgtm, approved, dco-signoff: yes

#243 [release-2.4] Update GRC UI refs to use new org
  Makefile
  build/clean-up-cluster.sh
  build/patch-dev-images.sh
  build/run-e2e-tests-ui.sh
  test/integration/policy_generator_test.go
Labels: lgtm, approved, dco-signoff: yes

#249 [release-2.2] Organization rename to `stolostron`
  Makefile
  build/patch-dev-images.sh
  build/patches/certpolicycontroller.json
  build/patches/iampolicycontroller.json
  build/patches/policycontroller.json
  build/run-e2e-tests.sh
  deploy/cert-policy-controller/operator.yaml
  deploy/config-policy-controller/operator.yaml
  deploy/iam-policy-controller/operator.yaml
  deploy/propagator/operator.yaml
  deploy/spec-sync/operator.yaml
  deploy/status-sync/yamls/operator.yaml
  deploy/template-sync/operator.yaml
Labels: lgtm, approved, dco-signoff: yes

#250 [release-2.2] Update GRC UI refs to use new org
  Makefile
  build/patch-dev-images.sh
  build/run-e2e-tests-ui.sh
Labels: lgtm, approved, dco-signoff: yes

#242 Update GRC UI refs to use new org
  Makefile
  build/clean-up-cluster.sh
  build/patch-dev-images.sh
  build/run-e2e-tests-ui.sh
  test/integration/policy_generator_test.go
Labels: lgtm, approved, dco-signoff: yes

#227 Periodic job that can be run to detect prow publish failures
  build/periodic.sh
Labels: lgtm, approved, dco-signoff: yes

#251 There's a problem with doing the git clones from prow
  build/periodic.sh
Labels: lgtm, approved, dco-signoff: yes
